### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by benawad** [benawad/dogehouse#386]
**Main Roadmap**
- Fix bugs
  -  https://github.com/benawad/dogehouse/projects/1#column-13063475
- Design a better UI
  - @ajmnz 
- Social features
  - [ ] alert followers when you create a new room [modal on website/browser notification]
  - [ ] notifications section to see who follows you and ability to follow back
  - [ ] after following someone, suggest who I should follow next
  - [x] schedule rooms
- Electron desktop app [3 defining features that are different from website]
  - [x] should be able to auto update when new versions are released
  - [x] global keybinds
  - [x] system notifications
- DogeSubscriptions [I want this to be crypto at first]
  - [ ] Crypto Subscriptions
  - [ ] Other subscriptions (TBD)

**Future Features (No specific order for these and no estimated timeframe)**
- API Stuff
  - [ ] API Updates ( #1371 )
- System Stuff 
  - [ ] Language Sync ( #1333 )
  - [ ] Sync sound effects and key binds ( #1333 )
  - [ ] Better default mute sound ( #1306 )
- Room/Social Features
  - [ ] Add support for filtering rooms (based on how long they've been around, number of members, etc. - ref: #1379 )
  - [ ] Add "recent activity" feed to profile page to show recent people who followed the user, recent people the user followed, and potentially other things (rooms been in, etc.)
  - [ ] Make it show a small popup of the profile after hovering over someone's name for a number of seconds ( #1314 )
- Mobile App
  - [ ] Create Mobile App

Also see https://github.com/benawad/dogehouse/projects/1 for a feature priority list

**Comment by a7medev** [comment]
Is there any plan for make it a mobile app?

**Comment by benawad** [comment]
yes, but I'm thinking after the website hits market-fit

**Comment by saumya66** [comment]
> yes, but I'm thinking after the website hits market-fit

Ya that's a good move !

**Comment by BoscoDomingo** [comment]
> 
> 
> yes, but I'm thinking after the website hits market-fit

Going with Kotlin/Swift, react-native, something else...? I'd love to contribute with my limited knowledge and web isn't my forte atm

**Comment by JDOG787** [comment]
react-native would be cool

**Comment by Rajatgurung** [comment]
Are we going to use react in Electron app

**Comment by TheOtterlord** [comment]
@Rajatgurung The Electron app is a wrapper for the website. (see the `baklava` directory)

**Comment by Rajatgurung** [comment]
ok I just found out.
