### ISSUE TITLE
Flatpak-based package for the Electron app

### ISSUE THREAD

**Issue by ajhalili2006** [benawad/dogehouse#933]
As @overlisted requested, I'll work also on the Flatpak package for the desktop app. And since I don't need yet another boilerplate just to package something into Flatpaks (unlike in Snaps, but we can generate the `snap` directory as part of `snapcraft init`) and to prevent people from asking their Linux sysadmins (in case of shared machines) just to install an snap package.

## To-Dos

* [x] Install Flatpak on my Ubuntu machine
* [ ] Fork the repo or shall I create an new branch from `upstream/staging` instead.
* [ ] TK - Update the todo list later

**Comment by ajmnz** [comment]
@AndreiJirohHaliliDev2006 Has this been fixed/done?

**Comment by ajhalili2006** [comment]
> @AndreiJirohHaliliDev2006 Has this been fixed/done?

@ajmnz Still not yet, but I'll add the flatpak config into `electron-builder` and test. Soon.
